### ISSUE TITLE
customer.createCard should be named customer.createSource

### ISSUE THREAD

**Issue by nicolaslopezj** [copleykj/meteor-stripe-sync#1]
Following stripe api docs there is no createCard method, it's named createSource.

https://stripe.com/docs/api/node#create_card

By the way, thanks for the package, is very useful.

**Comment by dkmooers** [comment]
This is an issue with mrgalaxy:stripe, actually. It's using an old version of the Stripe API. Trying to get this fixed...

**Comment by copleykj** [comment]
This is fixed in the current release. Also as of this release you won't need to include a separate stripe package as its now a dependency.

**Comment by dkmooers** [comment]
@copleykj Thanks, much appreciated!
