### ISSUE TITLE
Client-side Stripe scripts are broken

### ISSUE THREAD

**Issue by dkmooers** [copleykj/meteor-stripe-sync#3]
It looks like Stripe.js is being included:

https://github.com/copleykj/meteor-stripe-sync/blob/master/includes.html
https://github.com/copleykj/meteor-stripe-sync/blob/master/package.js

But I'm not seeing Stripe on my client. If I include those scripts manually in my template head, I can see it. Looks like the same implementation as mrgalaxy:stripe, so not exactly sure what's going on. Only difference I can see is a line break in your `includes.html` file? Doesn't seem like that would be a problem but I don't know...

When I look in the actual package in my ~/.meteor directory, I see that in mrgalaxy:stripe, the `web.browser` folder contains a file called "head", which just calls the two Stripe scripts. But when I look in the `web.browser` folder of your package, I don't see that "head" file. I have to go to `web.browser/packages` and then I see "includes.html". It's like the package isn't getting compiled correctly? Not sure how Meteor packages work, so just guessing here.

**Comment by copleykj** [comment]
Done.. Sorry it seems I needed to have a api.use call for templating so that it would compile the html file

**Comment by dkmooers** [comment]
Thanks for the quick fix!

**Comment by copleykj** [comment]
No problem.. Can't have that kind of an annoying issue lingering.
