### ISSUE TITLE
StripeAPI on server is broken

### ISSUE THREAD

**Issue by dkmooers** [copleykj/meteor-stripe-sync#4]
When I try this:

```
Stripe = StripeSync('key');
```

on the server, I get this:

```
ReferenceError: StripeAPI is not defined at StripeSync (packages/copleykj:stripe-sync/StripeSync.js:20:1)
```

Looks like you might need this (from mrgalaxy:stripe):

https://github.com/tyler-johnson/stripe-meteor/blob/master/stripe_server.js

And then add it to the server via api.use, like here:

https://github.com/tyler-johnson/stripe-meteor/blob/master/package.js

**Comment by copleykj** [comment]
Yes, I meant to add that but some how I missed it.

**Comment by copleykj** [comment]
Should be all set now. If not I'm going to retire :-P

**Comment by dkmooers** [comment]
We're cookin' with gas now!! :D
