### ISSUE TITLE
Return values within meteor methods are undefined on client.

### ISSUE THREAD

**Issue by vacarsu** [copleykj/meteor-stripe-sync#6]
When using the stripe methods within meteor methods the return values are always undefined on the client. If I log the value on the server, however, it logs the correct value. I researched why this could be happening. And found this on StackOverflow http://stackoverflow.com/questions/17460123/meteor-methods-returns-undefined

But as this package is called Stripe-Sync I assume all the stripe methods are synchronous, so I am at a loss as to why this is happening.

**Comment by copleykj** [comment]
This package makes server side calls to the StripeAPI synchronous. There is no way to make sync calls from the browser as the there is only a single thread and doing so would cause all other execution to halt until the call completed.

**Comment by vacarsu** [comment]
So it's not possible to get the return values to the client? That doesn't really make sense, my Meteor.Methods are on the server.

**Comment by copleykj** [comment]
Sure, you could call a Meteor method via `Meteor.call()` and return whatever you needed from that. The server method is still going to execute asynchronously, but the sync nature of the StripeAPI  will allow you to return the value where as if it was executed async on the server, the method would return before the API call completed and the return from the method would be undefined.

**Comment by vacarsu** [comment]
Okay, that makes more sense. So how then could I return the data for the client to use I need to display a customers subscription information? Overall I've got the package working very well, I just really need to be able to display information on the client.

**Comment by copleykj** [comment]
The StripeAPI call should return a response in json format which will be automatically converted to an object like so.

``` json
{
  "id": "sub_6iH2Ek8cCBt04p",
  "plan": {
    "interval": "month",
    "name": "New plan name",
    "created": 1386247539,
    "amount": 2000,
    "currency": "usd",
    "id": "gold21323",
    "object": "plan",
    "livemode": false,
    "interval_count": 1,
    "trial_period_days": null,
    "metadata": {
    },
    "statement_descriptor": null
  },
  "object": "subscription",
  "start": 1438399029,
  "status": "active",
  "customer": "cus_6iGJ9KtoFRv1w3",
  "cancel_at_period_end": false,
  "current_period_start": 1438399029,
  "current_period_end": 1441077429,
  "ended_at": null,
  "trial_start": null,
  "trial_end": null,
  "canceled_at": null,
  "quantity": 1,
  "application_fee_percent": null,
  "discount": null,
  "tax_percent": null,
  "metadata": {
  }
}
```

I personally would store any information needed on the user document, and then publish that info to the client for display. Otherwise you can return that object directly to the client from the method and it will be available as a the result param of the callback method.

``` javascript
Meteor.call("doSubscription", stripeSingleUseToken, function callback(error, result) {
    if(!error){
        //do something with result
    }else{
        //handle error
    }
});
```

**Comment by vacarsu** [comment]
Right, that is what I thought, and how I have it set up. However when I log the returned value on the client it's just undefined.
example Meteor Method

``` javascript
findCustomer: function() {
    Stripe.customers.retrieve(Meteor.user().profile.customerId, function(err, customer) {
      if (err)
        return console.log(err)

      return customer;
    })
  },
```

The client side call

``` javascript
$meteor.call('findCustomer')
.then(customer => {
  console.log(customer);
})
```

The client side call logs undefined and I seriously have no idea why if I log the customer object on the server however, it logs the object so I know the stripe call succeeds.

**Comment by copleykj** [comment]
Ok, in which case the problem is that you are still calling the API asychronously. Since the methods and use fibers you can just get the return value and assign it to a variable or return it from the method. To handle errors you have to use try/catch and throw a `Meteor.Error` which will be propagated to the client as the first param of the callback.

``` javascript
findCustomer: function() {
    try{
        return Stripe.customers.retrieve(Meteor.user().profile.customerId);
    }catch(error){
        throw new Meteor.Error("StripeAPIFailure", error.message);
    }
}
```

**Comment by vacarsu** [comment]
Awesome, that worked. Thank you very much for the help.

**Comment by copleykj** [comment]
You're very welcome

**Comment by vinaynb** [comment]
Facing a similar issue..i have 3 method calls in succession on server...i want to return response of 1st method call to the client after the last nested method call gets executed successfully. Right now i get undefined when i try to get the value in callback function on client..
Here's my method code:

```
Bills.insert(bill, function(error, response) {
                billId = response;
                if (error) {
                    throw new Meteor.Error(700, 'Something went wrong', error);
                }

                var orderDoc = Orders.findOne({ tableId: bill.tableId });
                Meteor.call('removeOrder', orderDoc._id, function(error) {
                    if (error) {
                        throw new Meteor.Error(700, 'Something went wrong', error);
                    }

                    var fields = {
                        orderId: ''
                    };

                    Meteor.call("updateTable", bill.tableId, fields, function(error) {
                        if (!error) {
                            throw new Meteor.Error(700, 'Something went wrong', error);
                        }
                        return billId;
                    });
                });
            });
```

Any pointers as to what's wrong with the way i am returning the value ?
