### ISSUE TITLE
stripe.subscriptions.update() is undefined

### ISSUE THREAD

**Issue by sproleee** [copleykj/meteor-stripe-sync#8]
I can't seem to be able to update subscriptions with this package.

What API version does this package use? Must be outdated since I can't get the current API documentation to jive with this Meteor package.

Any help would be appreciated.

**Comment by copleykj** [comment]
Yes this is a little outdated at 3.7.1. I was going to put in the work to update this, but then meteor implemented support for npm packages and async/await which allows you to accomplish the same thing by just adding stripe from npm.

**Comment by sproleee** [comment]
Do you know the older method for the subscription update or does it not exist in the older API?

**Comment by copleykj** [comment]
I believe it was `stripe.customers.updateSubscription(customerId, subscriptionId, [params])`
