### ISSUE TITLE
Replace with await and async?

### ISSUE THREAD

**Issue by MichaelJCole** [copleykj/meteor-stripe-sync#9]
Hi, I used your package so thanks! 

Time marches on.  This [blog post talks about how to use await/async to basically do the same thing](https://blog.meteor.com/using-promises-and-async-await-in-meteor-8f6f4a04f998#.vg7k39z9y).  

Might be worth adding to the README.

**Comment by copleykj** [comment]
Should be all set now. Thanks for the heads up :)
